- name: Install deps
  run: |
    npm ci || npm i
    npx playwright install --with-deps chromium

- name: Download XLSX and upload to site (headless)
  env:
    LEGHE_EMAIL: ${{ secrets.LEGHE_EMAIL }}
    LEGHE_PASSWORD: ${{ secrets.LEGHE_PASSWORD }}
    UPLOAD_URL: ${{ secrets.UPLOAD_URL }}
    UPLOAD_TOKEN: ${{ secrets.UPLOAD_TOKEN }}
    DEBUG: pw:api              # log Playwright ad alto livello
  run: node scripts/download_leghe_rosters_ci.mjs

# se lo script salverà screenshot/log, li carichiamo sempre come artifact
- name: Upload debug artifacts
  if: always()
  uses: actions/upload-artifact@v4
  with:
    name: debug-artifacts
    path: |
      cache/**
      negher rosters.xlsx
      debug/**
    if-no-files-found: ignore
